service: fylz-api
frameworkVersion: '>=1.28.0 <2.0.0'
provider:
  name: aws
  runtime: go1.x
  stage: prod
  custom:
    bucketName: fylz-files
  environment:
    S3_REGION: us-east-1
    S3_BUCKET: ${self:provider.custom.bucketName}
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action: [ "s3:ListBucket", "s3:PutObject", "s3:GetObject", "s3:DeleteObject", ]
      Resource: arn:aws:s3:::${self:provider.custom.bucketName}/*
    - Effect: "Allow"
      Action: [ "s3:ListBucket" ]
      Resource: arn:aws:s3:::${self:provider.custom.bucketName}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/api/upload
    events:
      - http:
          path: api/files
          method: post
  download:
    handler: bin/api/download
    events:
      - http:
          path: api/files/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
  url:
    handler: bin/api/url
    events:
      - http:
          path: api/url/{action}
          method: get
          request: 
            parameters: 
              paths: 
                action: true
  list:
    handler: bin/api/list
    events:
      - http:
          path: api/files
          method: get

Resources:
  IamRoleLambdaExecution:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
                - apigateway.amazonaws.com
  FileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.custom.bucketName}