service: fylz-api

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action: [ "s3:ListBucket", "s3:PutObject", "s3:GetObject", "s3:DeleteObject", ]
      Resource: "arn:aws:s3:::fylz-files/*"
    - Effect: "Allow"
      Action: [ "s3:ListBucket" ]
      Resource: "arn:aws:s3:::fylz-files"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  upload:
    handler: bin/upload
    events:
      - http:
          path: api/files
          method: post
  download:
    handler: bin/download
    events:
      - http:
          path: api/files/{id}
          method: get
          request: 
            parameters: 
              paths: 
                id: true
  url:
    handler: bin/url
    events:
      - http:
          path: api/files/{action}/url
          method: get
          request: 
            parameters: 
              paths: 
                action: true
  list:
    handler: bin/list
    events:
      - http:
          path: api/files
          method: get

Resources:
  IamRoleLambdaExecution:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement: 
          - Effect: Allow
            Principal: 
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
                - apigateway.amazonaws.com
  FileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fylz-files